
sudo: required
dist: trusty

language: c

before_install:
  - |
    DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  # Get cmake v3.6
  - CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cd ..

  # Get rust
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - export PATH=~/.cargo/bin:${PATH}
  - rustup component add rust-src

  # Get xargo
  - cargo install xargo

  # Pystache needed for generation of MourOS diagnostic code
  - sudo pip install pystache

  # Create the build directories
  - |
    mkdir build
    mkdir build/install

  # Needed for generation of coverage reports
  - sudo pip install gcovr

install:
  # Install libopencm3
  - ./build_libopencm3.sh ./build/install

before_script:
  # Generate the makefiles
  - |
    mkdir build/mouros
    mkdir build/mouros-tests

  - cd build/mouros
  - cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_TOOLCHAIN_FILE=../../cmake/arm-none-eabi-toolchain.cmake -DCHIP_FAMILY=STM32F0 -DCMAKE_BUILD_TYPE=Debug ../..
  - cd ../..

  - cd build/mouros-tests
  - cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_TOOLCHAIN_FILE=../../cmake/gcc-linux-x86-toolchain.cmake ../../tests
  - cd ../..


script:
  # Build it
  - cmake --build build/mouros --clean-first
  # Build docs
  - cmake --build build/mouros --target mouros-doc
  # Build & run tests
  - cmake --build build/mouros-tests --clean-first && cmake --build build/mouros-tests --target test
  # Generate coverage
  - cmake --build build/mouros-tests --target coverage
  # Build the Rust bindings library
  - cd rust
  - xargo build --target thumbv6m-none-eabi --lib
  - cd ..

addons:
  apt:
    packages:
      # arm-none-eabi gcc & newlib
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      # 32 bit compiler used for compiling tests
      - gcc-multilib
      # Documentation tools
      - doxygen
      - graphviz
